format_version: 10
pipelines:
  GoCD-pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-3269402:
        git: https://github.com/bilalahmed55/gocd
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -altr
                command: ls
                run_if: passed
            - exec:
                command: pwd
                run_if: passed
